# Python: Aufgaben zur Vorbereitung

* Autor: Prof. Dr. Johannes Maucher
* Datum: 13.10.2015
* [Download des Jupyter Notebooks (.ipynb)](Aufgaben zur Einarbeitung in das Data Mining Praktikum.ipynb) Klick auf _Ziel speichern unter_. Im Verzeichnis, in dem das Notebook abgelegt wurde, Konsole öffnen und dort _jupyter notebook_ eingeben.

[Übersicht Jupyter Notebooks im Data Mining Praktikum (.html)](Data Mining Praktikum.html)


## Listen
**Aufgaben:**
1. Legen Sie zwei Listen gleicher Länge mit numerischen Datenelementen an.

In [130]:
list1 = range(3,9,)
list2 = range(1,7)
print str(len(list1)) + " " + str(len(list2))

6 6


2. Hängen Sie an die erste Liste die Elemente der zweiten Liste an.

In [131]:
list3 = list1+list2
print list3

[3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6]


3. Suchen Sie in der neuen Liste nach einem Element mit einem bestimmten Wert und bestimmen Sie an welcher Position das Element in der Liste auftritt. Wie kann der Fall, dass der vorgegebene Wert nicht in der Liste ist, abgefangen werden?

In [189]:
def printSafeIndex(obj,list):
    if obj in list:
        print list.index(obj)
    else:
        print "not found"
    return

printSafeIndex(6,list3)

3


4. Löschen Sie die Elemente von der zweiten bis zur vierten Stelle aus der Liste (Elemente an den Indizes 1,2 und 3)

In [190]:
del list3[1:4]
print list3

[3, 7, 8, 1, 2, 3, 4, 5, 6]


4. Fügen Sie die Elemente 4,2 und 1 an der Stelle 2 fortfolgend ein (so dass Liste erweitert wird)

In [192]:
x=[4,2]
for i in range(0,len(x)):
    x.reverse()
    list3.insert(2,x[i])
    
print list3


[3, 7, 2, 2, 2, 2, 8, 1, 2, 3, 4, 5, 6]


5. Sortieren Sie die Liste nach absteigenden Werten.

In [193]:
list3.sort(reverse=True)

6. Berechnen Sie die elementweise Summe zweier numerischer Listen gleicher Länge mithilfe einer _List-Comprehension_.

In [194]:
list4 = list3[:]
list5 = list3[:]

for index,num in enumerate(list3):
    list5[index]  = num+list4[index]
print list5

[16, 14, 12, 10, 8, 6, 6, 4, 4, 4, 4, 4, 2]


## Strings
**Aufgaben:**

1. Weisen Sie einen Text mit mindestens 10 Wörtern einer Stringvariablen _text1_ zu.

text1 = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. "

2. Transformieren Sie _text1_ so, dass alle Wörter klein geschrieben sind.

In [5]:
text1 = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit"
text1.lower()

'lorem ipsum dolor sit amet, consectetuer adipiscing elit'

3. Aus wievielen Zeichen besteht der Text?

In [6]:
print len(text1)

56


4. Aus wievielen unterschiedlichen Zeichen besteht der Text?

In [7]:
s = set(text1)
print s, len(s)

set(['a', ' ', 'c', 'e', 'd', 'g', 'i', 'm', 'L', 'o', 'l', 'p', 's', 'r', 'u', 't', 'n', ',']) 18


1. Zerlegen Sie den in der String-Variablen abgespeicherten Text in eine Liste _list1_ von Wörtern.

In [8]:
l1 = text1.split()
print l1

['Lorem', 'ipsum', 'dolor', 'sit', 'amet,', 'consectetuer', 'adipiscing', 'elit']


2. Aus wievielen Wörtern besteht der Text?

In [9]:
print len(l1)

8


3. Aus wievielen unterschiedlichen Wörtern besteht der Text?

In [10]:
s2 = set()
for i,n in enumerate(l1):
    s2.add(n)
print s2, len(s2)

set(['ipsum', 'amet,', 'sit', 'elit', 'adipiscing', 'dolor', 'consectetuer', 'Lorem']) 8


1. Legen Sie analog zu _text1_ noch zwei weitere Stringvariablen _text2_ und _text3_ an, die ungefähr so viele Wörter enthalten wie _text1_.

In [97]:
text1 = "Lorem ipsum dolor dolor dolor sit amet, consectetuer adipiscing elit."
text2 = "Aenean commodo ligula eget dolor Aenean massa."
text3 = "Cum sociis natoque penatibus et magnis dis parturient montes"

2. Wiederholen Sie die oben genannten Schritte für _text2_ und _text3_. Die zugehörigen Wortlisten sollten mit _liste2_ und _liste3_ bezeichnet werden.

In [86]:
import re
def getWortSet(text):
    text = text.lower()
    text = delPunkte(text)
    text.strip(".")
    l = re.split('[ |\. |\, ]+', text, flags=re.IGNORECASE)
    s = set()
    for i,n in enumerate(l):
        s.add(n)
    return s



In [87]:
print getWortSet(text1+text2+text3)

set(['elit', 'et', 'ligula', 'natoque', 'sit', 'lorem', 'massa', 'cum', 'montes', 'commodo', 'eget', 'parturient', 'amet', 'aenean', 'ipsum', 'sociis', 'penatibus', 'adipiscing', 'dolor', 'consectetuer', 'magnis', 'dis'])


3. Bestimmen Sie jetzt das gesamte Vokabular. Das gesamte Vokabular ist die Menge aller Worte, die mindestens in einem der 3 Texte vorkommen. Die Wörter des Vokabulars sollen in einer Liste _vocabular_ gespeichert werden. Aus wievielen Wörtern besteht das Vokabular?

In [49]:
print len(getWortSet(text1+text2+text3))

22


## Dictionaries
**Aufgaben:**

1. Legen Sie für jeden der 3 Texte je ein Dictionary an, das als Keys alle Wörter des gesamten Vokabulars enthält und als Values die Häufigkeit des Worts im jeweiligen Text.

In [109]:
def getWortDict(text):
    text = text.lower()
    woerter = text.split()
    dict = {}

    for i in range(0,len(woerter)):
        if dict.setdefault(woerter[i],0) >= 0:
            dict[woerter[i]] += 1
                
    return dict
                
texte=[text1,text2,text3]     
for i,text in enumerate(texte):
    print getWortDict(text)

{'ipsum': 1, 'amet,': 1, 'sit': 1, 'elit.': 1, 'adipiscing': 1, 'dolor': 3, 'consectetuer': 1, 'lorem': 1}
{'commodo': 1, 'eget': 1, 'aenean': 2, 'dolor': 1, 'massa.': 1, 'ligula': 1}
{'natoque': 1, 'montes': 1, 'sociis': 1, 'penatibus': 1, 'et': 1, 'cum': 1, 'magnis': 1, 'parturient': 1, 'dis': 1}


2. Legen Sie ein verschachteltes Dictionary an, dessen Keys Namen für die drei oben angelegten Texte sind und dessen Values die oben angelegten Dictionarys sind.

In [104]:
alleTexte= {"text1": getWortDict(text1), "text2": getWortDict(text2), "text3": getWortDict(text3)}

3. Fragen Sie die Häufigkeit eines im Vokabular enthaltenen Worts in jedem der 3 Texte aus dem verschachtelten Dictionary ab.

In [108]:
print alleTexte["text1"]["dolor"]
print alleTexte["text2"]["dolor"]
print alleTexte["text3"]["montes"]

3
1
1


## Funktionen
**Aufgaben:**
1. Schreiben Sie eine Funktion, der eine Liste mit beliebig vielen Texten in Form von Stringvariablen übergeben wird. Aus dieser Liste soll ein verschachteltes Dictionary erzeugt und zurückgegeben werden, das als Keys Namen für die einzelnen Texte enthält und dessen Values Dictionaries sind, welche die Häufigkeit der Vokabularworte in den jeweiligen Texten enthalten (also das gleiche verschachtelte Dictionary, wie in der vorigen Aufgabe für 3 Texte angelegt wurde).

In [125]:
def getBigDict(*args):
    d = {}
    for i,arg in enumerate(args):
        d.setdefault("text"+str(i),getWortDict(arg))
    return d

2. Legen Sie eine Liste von Texten (Stringvariablen) an, übergeben Sie diese der oben implementierten Funktion und geben Sie das von der Funktion zurückgegebene verschachtelte Dictionary aus.

In [126]:
print getBigDict(text1,text2,text3)

{'text2': {'natoque': 1, 'montes': 1, 'sociis': 1, 'penatibus': 1, 'et': 1, 'cum': 1, 'magnis': 1, 'parturient': 1, 'dis': 1}, 'text0': {'ipsum': 1, 'amet,': 1, 'sit': 1, 'elit.': 1, 'adipiscing': 1, 'dolor': 3, 'consectetuer': 1, 'lorem': 1}, 'text1': {'commodo': 1, 'eget': 1, 'aenean': 2, 'dolor': 1, 'massa.': 1, 'ligula': 1}}


# Numpy: Aufgaben zur Vorbereitung

[Numpy Intro IPython Notebook](http://nbviewer.ipython.org/github/jrjohansson/scientific-python-lectures/blob/master/Lecture-2-Numpy.ipynb)

1. Wie wird ein eindimensionales, wie ein zweidimensionales Numpy Array angelegt?
2. Wie bestimmt man die Größe (Anzahl Zeilen und Anzahl Spalten) eines zweidimensionalen Numpy Arrays?

In [148]:
%matplotlib inline
import matplotlib.pyplot as plt

from numpy import *

v = array([1,2,3,4])

print v

m = array([[1,2,3],[3,4,5],[1,2,3],[3,4,5]])

print m

print v.shape
print m.shape



[1 2 3 4]
[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]
(4L,)
(4L, 3L)


3. Wie werden die Mittelwerte der Spalten eines Numpy Arrays ermittelt, wie werden die Standardabweichungen der Spalten eines Numpy Arrays berechnet?

In [189]:
print mean(a[:,2])
print std(a[1,:])

5.0
0.816496580928


4. Wie können die Daten aus einem .csv File direkt in ein Numpy-Array eingelesen werden?

In [140]:
# data = genfromtxt('BEISPIEL NAME')

5. Wie kann ein Numpy Array effizient in einem File abgespeichert werden? Wie können diese Daten aus dem File wieder in ein Numpy Array gelesen werden?

In [ ]:
# SAVE save("BEISPIEL.npy", M)
# LOAD load("BEISPIEL.npy")

6. Wie kann auf das Element in Zeile 1, Spalte 2 eines Numpy Arrays zugegriffen werden?

In [ ]:
print m[0,1]

7. Wie kann auf die zweite Zeile eines Numpy-Arrays zugegriffen werden?

In [144]:
print m[:,1]

[2 4]


8. Wie kann auf die Spalten 2 bis 4 eines Numpy-Arrays zugegriffen werden?

In [149]:
print m[:,2:4]

[[3]
 [5]
 [3]
 [5]]


8. Wie kann das Skalarprodukt zweier eindimensionaler Numpy-Arrays bestimmt werden? 

In [154]:
a = array([1,2,3,4,5,6])
b = array([7,8,9,10,11,12])

dot(a,b)

217

9. Wie kann ein zweidimensionales Numpy-Array mit einem anderen zweidimensionales Numpy-Array multipliziert werden (im Sinne einer Matrixmultiplikation)? 

In [164]:
a = array([[1,2],[11,12]])
b = array([[4,5],[8,9]])

print dot(a,b)

[[ 20  23]
 [140 163]]


10. Wie kann ein eindimensionales Numpy Array mit einem zweidimensionalen Numpy Array multipliziert werden?

In [165]:
a = array([1,2])
b = array([[4,5],[8,9]])

print dot(a,b)

[20 23]


11. Wie können Zeilen oder Spalten eines Numpy Arrays hinsichtlich ihrer Werte ansteigend oder absteigend sortiert werden?

In [178]:
a = array([[1,4], [3,1]])
a.sort(axis=1)
print a

a.sort(axis=0)
print a

[[1 4]
 [1 3]]
[[1 3]
 [1 4]]


# Scipy: Aufgaben zur Vorbereitung

[SciPy Intro IPython Notebook](http://nbviewer.ipython.org/github/jrjohansson/scientific-python-lectures/blob/master/Lecture-3-Scipy.ipynb)

Machen Sie sich mit den Funktionen des Moduls [Scipy.spatial.distance](http://docs.scipy.org/doc/scipy-0.14.0/reference/spatial.distance.html#module-scipy.spatial.distance) vertraut.

1. Wie wird die paarweise euklidische Distanz zwischen den Zeilen eines Numpy Array berechnet?

In [191]:
# what is this line all about? Answer in lecture 4
%matplotlib inline
import matplotlib.pyplot as plt
from scipy import *
from scipy.spatial import distance

a = array([[1,2],[9,8]])

print distance.euclidean(a[:,0], a[0,:])


7.0


Machen Sie sich mit den Funktionen des Moduls [Scipy.cluster.hierarchy](http://docs.scipy.org/doc/scipy/reference/cluster.hierarchy.html) vertraut.

1. Wie wird mit diesem Modul ein hierarchisches Clustering von Vektoren berechnet und visualisiert?
2. Welche Bedeutung haben die Parameter _method_ und _metric_ der Funktion _linkage_?  

# Matplotlib: Aufgaben zur Vorbereitung

[Matplotlib Intro IPython Notebook](http://nbviewer.ipython.org/github/jrjohansson/scientific-python-lectures/blob/master/Lecture-4-Matplotlib.ipynb)

1. Machen Sie sich anhand des oben verlinkten Matplotlib mit den grundlegenden Plotting Funktionen dieses Pakets vertraut.



# Pandas: Aufgaben zur Vorbereitung

[10 Minutes to Pandas](http://pandas.pydata.org/pandas-docs/stable/10min.html)

1. Was ist der Vorteil eines Pandas Dataframe gegenüber einem Numpy Array?
2. Wie legt man eine Pandas Dataframe an?
3. Wie liest man eine .csv Datei in einen Pandas Dataframe?
4. Wie schreibt man einen Pandas Dataframe in eine .csv Datei?
4. Wie greift man auf den Index eines Pandas Dataframes zu?
4. Wie greift man auf die Spaltennamen eines Dataframes zu?
5. Wie greift man auf eine Spalte eines Dataframes zu?
6. Wie greift man auf eine Zeile eines Dataframes zu?