# Python: Aufgaben zur Vorbereitung

* Autor: Prof. Dr. Johannes Maucher
* Datum: 13.10.2015
* [Download des Jupyter Notebooks (.ipynb)](Aufgaben zur Einarbeitung in das Data Mining Praktikum.ipynb) Klick auf _Ziel speichern unter_. Im Verzeichnis, in dem das Notebook abgelegt wurde, Konsole öffnen und dort _jupyter notebook_ eingeben.

[Übersicht Jupyter Notebooks im Data Mining Praktikum (.html)](Data Mining Praktikum.html)


## Listen
**Aufgaben:**
1. Legen Sie zwei Listen gleicher Länge mit numerischen Datenelementen an.
2. Hängen Sie an die erste Liste die Elemente der zweiten Liste an.
3. Suchen Sie in der neuen Liste nach einem Element mit einem bestimmten Wert und bestimmen Sie an welcher Position das Element in der Liste auftritt. Wie kann der Fall, dass der vorgegebene Wert nicht in der Liste ist, abgefangen werden?
4. Löschen Sie die Elemente von der zweiten bis zur vierten Stelle aus der Liste (Elemente an den Indizes 1,2 und 3)
5. Fügen Sie die Elemente 4,2 und 1 an der Stelle 2 fortfolgend ein (so dass Liste erweitert wird)
6. Sortieren Sie die Liste nach absteigenden Werten.
7. Berechnen Sie die elementweise Summe zweier numerischer Listen gleicher Länge mithilfe einer _List-Comprehension_.

In [40]:
#1
l1=[1,2,3,4]
l2=[5,6,7,8]

#2
l1.extend(l2)
print l1

#3
val=7
if val not in l1:
    print "sorry bruh"
else:
    print l1.index(val)

#4
del l1[1:4]
print l1

#5
l3=[4,2,1]
l1[1:1]=l3
print l1

#6
l1.sort(reverse=True)
print l1

#7
l4=range(9)
print l4
sum1=0;
sum4=0;
for index,a in enumerate(l1):
    sum1+=a
    sum4+=l4[index]
print sum1
print sum4

[1, 2, 3, 4, 5, 6, 7, 8]
6
[1, 5, 6, 7, 8]
[1, 4, 2, 1, 5, 6, 7, 8]
[8, 7, 6, 5, 4, 2, 1, 1]
[0, 1, 2, 3, 4, 5, 6, 7, 8]
34
28


## Strings
**Aufgaben:**

1. Weisen Sie einen Text mit mindestens 10 Wörtern einer Stringvariablen _text1_ zu.
2. Transformieren Sie _text1_ so, dass alle Wörter klein geschrieben sind.
3. Aus wievielen Zeichen besteht der Text?
4. Aus wievielen unterschiedlichen Zeichen besteht der Text?
1. Zerlegen Sie den in der String-Variablen abgespeicherten Text in eine Liste _list1_ von Wörtern.
2. Aus wievielen Wörtern besteht der Text?
3. Aus wievielen unterschiedlichen Wörtern besteht der Text?
1. Legen Sie analog zu _text1_ noch zwei weitere Stringvariablen _text2_ und _text3_ an, die ungefähr so viele Wörter enthalten wie _text1_.
2. Wiederholen Sie die oben genannten Schritte für _text2_ und _text3_. Die zugehörigen Wortlisten sollten mit _liste2_ und _liste3_ bezeichnet werden.
3. Bestimmen Sie jetzt das gesamte Vokabular. Das gesamte Vokabular ist die Menge aller Worte, die mindestens in einem der 3 Texte vorkommen. Die Wörter des Vokabulars sollen in einer Liste _vocabular_ gespeichert werden. Aus wievielen Wörtern besteht das Vokabular?

In [9]:
#1
text1 = "Simon war ein kleiner Idiot. Er liebte es, Klebstoff zu schnüffeln"

#2
text1 = text1.lower()
print text1

#3
print 'Mit whitespaces besteht text1 aus',len(text1),' Zeichen.'
text1_1=text1[:]
print text1_1
text1_1=text1_1.replace(" ","")
print 'Ohne nur aus ',len(text1_1)

#4
def unterschiedlicheZeichen(s):
    Buchstabenmenge=set(s)
    print len(Buchstabenmenge)
unterschiedlicheZeichen(text1)

#5
list1 = text1.split()
print list1

#6
print len(list1)

#7
m_list1 = set(list1)
print len(m_list1)

#8
text2="Ich mag Tomaten und Bananen. Ich esse sie täglich"
text3="der die das der die das der die das kartoffel"

#9
list2 = text2.split()
m_list2 = set(list2)
print len(m_list2)

list3 = text3.split()
m_list3 = set(list3)
print len(m_list3)


simon war ein kleiner idiot. er liebte es, klebstoff zu schnüffeln
Mit whitespaces besteht text1 aus 67  Zeichen.
simon war ein kleiner idiot. er liebte es, klebstoff zu schnüffeln
Ohne nur aus  57
24
['simon', 'war', 'ein', 'kleiner', 'idiot.', 'er', 'liebte', 'es,', 'klebstoff', 'zu', 'schn\xc3\xbcffeln']
11
11
8
4


## Dictionaries
**Aufgaben:**

1. Legen Sie für jeden der 3 Texte je ein Dictionary an, das als Keys alle Wörter des gesamten Vokabulars enthält und als Values die Häufigkeit des Worts im jeweiligen Text.
2. Legen Sie ein verschachteltes Dictionary an, dessen Keys Namen für die drei oben angelegten Texte sind und dessen Values die oben angelegten Dictionarys sind.
3. Fragen Sie die Häufigkeit eines im Vokabular enthaltenen Worts in jedem der 3 Texte aus dem verschachtelten Dictionary ab.

In [26]:
import re

#1
def senToDict(sentence):
    d={}
    sentence.replace(",","")
    sentence.replace(".","")
    wordlist= sentence.split()
    
    for index, val in enumerate(wordlist):
        d.setdefault(wordlist[index], sentence.count(wordlist[index]))
    return d

dic_text1=senToDict(text1)
dic_text2=senToDict(text2)
dic_text3=senToDict(text3)

print dic_text1
print dic_text2
print dic_text3

#2
def motherDict(*args):
    d={}
    for i, v in enumerate(args):
        d.setdefault(i, v)
    return d

mommy= motherDict(dic_text1, dic_text2, dic_text3)
print mommy

#3
totalVoc= set.union(m_list1, m_list2, m_list3)
print mommy[0]["simon"]
print mommy[1]["Ich"]
print mommy[2]["das"]

{'klebstoff': 1, 'simon': 1, 'schn\xc3\xbcffeln': 1, 'es,': 1, 'liebte': 1, 'idiot.': 1, 'kleiner': 1, 'zu': 1, 'ein': 2, 'war': 1, 'er': 2}
{'Ich': 2, 'sie': 1, 'Tomaten': 1, 't\xc3\xa4glich': 1, 'esse': 1, 'mag': 1, 'und': 1, 'Bananen.': 1}
{'die': 3, 'der': 3, 'kartoffel': 1, 'das': 3}
{0: {'klebstoff': 1, 'simon': 1, 'schn\xc3\xbcffeln': 1, 'es,': 1, 'liebte': 1, 'idiot.': 1, 'kleiner': 1, 'zu': 1, 'ein': 2, 'war': 1, 'er': 2}, 1: {'Ich': 2, 'sie': 1, 'Tomaten': 1, 't\xc3\xa4glich': 1, 'esse': 1, 'mag': 1, 'und': 1, 'Bananen.': 1}, 2: {'die': 3, 'der': 3, 'kartoffel': 1, 'das': 3}}
1
2
3


## Funktionen
**Aufgaben:**
1. Schreiben Sie eine Funktion, der eine Liste mit beliebig vielen Texten in Form von Stringvariablen übergeben wird. Aus dieser Liste soll ein verschachteltes Dictionary erzeugt und zurückgegeben werden, das als Keys Namen für die einzelnen Texte enthält und dessen Values Dictionaries sind, welche die Häufigkeit der Vokabularworte in den jeweiligen Texten enthalten (also das gleiche verschachtelte Dictionary, wie in der vorigen Aufgabe für 3 Texte angelegt wurde).
2. Legen Sie eine Liste von Texten (Stringvariablen) an, übergeben Sie diese der oben implementierten Funktion und geben Sie das von der Funktion zurückgegebene verschachtelte Dictionary aus.

In [ ]:
#1
#schon erledigt in Aufgabe 2 bei DIctionaries

# Numpy: Aufgaben zur Vorbereitung

[Numpy Intro IPython Notebook](http://nbviewer.ipython.org/github/jrjohansson/scientific-python-lectures/blob/master/Lecture-2-Numpy.ipynb)

1. Wie wird ein eindimensionales, wie ein zweidimensionales Numpy Array angelegt?

In [109]:
from numpy import *
a = array([1,2,3,4])
print a

[1 2 3 4]


2. Wie bestimmt man die Größe (Anzahl Zeilen und Anzahl Spalten) eines zweidimensionalen Numpy Arrays?

In [15]:
b = array([[1,2],[3,4]])
print b
print b.shape
print b.size

###TEST###
c = array([[1,2,3],[4,5]])
print c
print c.shape
print c.size


[[1 2]
 [3 4]]
(2L, 2L)
4
[[1, 2, 3] [4, 5]]
(2L,)
2


3. Wie werden die Mittelwerte der Spalten eines Numpy Arrays ermittelt, wie werden die Standardabweichungen der Spalten eines Numpy Arrays berechnet?

In [8]:
print mean(a[:,])

2.5


4. Wie können die Daten aus einem .csv File direkt in ein Numpy-Array eingelesen werden?

In [19]:
data = array([])
data = getfromtext('<datei>')

5. Wie kann ein Numpy Array effizient in einem File abgespeichert werden? Wie können diese Daten aus dem File wieder in ein Numpy Array gelesen werden?

In [20]:
### Als csv ###
M = random.rand(3,3)
savetxt("random-matrix-test.csv", M)

### als npy ###
save('random-matrix.npy', M)

N = load('random-matrix.npy')
print N

[[ 0.80272648  0.39972117  0.22048659]
 [ 0.05829838  0.07413952  0.15681029]
 [ 0.62643348  0.37918317  0.95344747]]


6. Wie kann auf das Element in Zeile 1, Spalte 2 eines Numpy Arrays zugegriffen werden?

In [21]:
print M[0,1]

0.39972116505


7. Wie kann auf die zweite Zeile eines Numpy-Arrays zugegriffen werden?

In [22]:
print M[1]

[ 0.05829838  0.07413952  0.15681029]


9. Wie kann auf die Spalten 2 bis 4 eines Numpy-Arrays zugegriffen werden?

In [23]:
N4 = random.rand(4,4)
print N4
print "###"
print N4[:,1]

[[ 0.0570107   0.96911216  0.54655743  0.8847423 ]
 [ 0.6305681   0.75708875  0.2618624   0.24243757]
 [ 0.38271842  0.94091627  0.66326507  0.48625265]
 [ 0.04105871  0.27581979  0.70947606  0.42574996]]
###
[ 0.96911216  0.75708875  0.94091627  0.27581979]


10. Wie kann das Skalarprodukt zweier eindimensionaler Numpy-Arrays bestimmt werden? 

In [26]:
S1 = array([1,2])
S2 = array([3,4])

def skalP(a1,a2):
    p = 0
    for i, v in enumerate(a1):
        p+= v * a2[i]
    return p

print skalP(S1,S2)
        

11


11. Wie kann ein zweidimensionales Numpy-Array mit einem anderen zweidimensionales Numpy-Array multipliziert werden (im Sinne einer Matrixmultiplikation)? 

In [77]:
S3= array([[1,2],[3,4]])
S4= array([[1,2],[3,4]])

dot(S3, S4)

array([[ 7, 10],
       [15, 22]])

11. Wie kann ein eindimensionales Numpy Array mit einem zweidimensionalen Numpy Array multipliziert werden?

In [83]:
S5= array([1,9])
dot(S3,S1)

array([ 5, 11])

12. Wie können Zeilen oder Spalten eines Numpy Arrays hinsichtlich ihrer Werte ansteigend oder absteigend sortiert werden?

In [105]:
xyz = random.rand(5,5)
print 'xyz:\n',xyz
print
print 'Nach Spalten sortieren mit axis=0'
xyz.sort(axis=0)
print xyz
print
print 'Nach Reihe sortieren mit axis=1'
xyz.sort(axis=1)
print xyz


xyz:
[[ 0.88651186  0.65732345  0.37238767  0.65525565  0.94216723]
 [ 0.08778483  0.38360926  0.29419214  0.97567118  0.59827598]
 [ 0.62993759  0.28572156  0.5056401   0.32074291  0.6474853 ]
 [ 0.15357451  0.55467851  0.1034907   0.98392512  0.39949261]
 [ 0.8411938   0.2608071   0.56599069  0.10512174  0.9801349 ]]

Nach Spalten sortieren mit axis=0
[[ 0.08778483  0.2608071   0.1034907   0.10512174  0.39949261]
 [ 0.15357451  0.28572156  0.29419214  0.32074291  0.59827598]
 [ 0.62993759  0.38360926  0.37238767  0.65525565  0.6474853 ]
 [ 0.8411938   0.55467851  0.5056401   0.97567118  0.94216723]
 [ 0.88651186  0.65732345  0.56599069  0.98392512  0.9801349 ]]

Nach Reihe sortieren mit axis=1
[[ 0.08778483  0.1034907   0.10512174  0.2608071   0.39949261]
 [ 0.15357451  0.28572156  0.29419214  0.32074291  0.59827598]
 [ 0.37238767  0.38360926  0.62993759  0.6474853   0.65525565]
 [ 0.5056401   0.55467851  0.8411938   0.94216723  0.97567118]
 [ 0.56599069  0.65732345  0.88651186  0.98

# Scipy: Aufgaben zur Vorbereitung

[SciPy Intro IPython Notebook](http://nbviewer.ipython.org/github/jrjohansson/scientific-python-lectures/blob/master/Lecture-3-Scipy.ipynb)

Machen Sie sich mit den Funktionen des Moduls [Scipy.spatial.distance](http://docs.scipy.org/doc/scipy-0.14.0/reference/spatial.distance.html#module-scipy.spatial.distance) vertraut.

In [117]:
import numpy
import scipy.spatial.distance as ssd

1. Wie wird die paarweise euklidische Distanz zwischen den Zeilen eines Numpy Array berechnet?

In [119]:
ea1= array([1,2])
ea2= array([3,4])
ssd.euclidean(ea1, ea2)


2.8284271247461903

Machen Sie sich mit den Funktionen des Moduls [Scipy.cluster.hierarchy](http://docs.scipy.org/doc/scipy/reference/cluster.hierarchy.html) vertraut.

1. Wie wird mit diesem Modul ein hierarchisches Clustering von Vektoren berechnet und visualisiert?

In [ ]:
fcluster(Z, t[, criterion, depth, R, monocrit])

2. Welche Bedeutung haben die Parameter _method_ und _metric_ der Funktion _linkage_?  

In [ ]:
Methode: welcher Algorithmus verwendet werden soll
Metric:  Masseinheit

# Matplotlib: Aufgaben zur Vorbereitung

[Matplotlib Intro IPython Notebook](http://nbviewer.ipython.org/github/jrjohansson/scientific-python-lectures/blob/master/Lecture-4-Matplotlib.ipynb)

1. Machen Sie sich anhand des oben verlinkten Matplotlib mit den grundlegenden Plotting Funktionen dieses Pakets vertraut.

In [13]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from pylab import *
print "done"

done


In [23]:
x = np.linspace(0, 5, 10)
y = x ** 2
figure()
plot(x, y, 'r')
xlabel('x')
ylabel('y')
title('title')
show()

# Pandas: Aufgaben zur Vorbereitung

[10 Minutes to Pandas](http://pandas.pydata.org/pandas-docs/stable/10min.html)

1. Was ist der Vorteil eines Pandas Dataframe gegenüber einem Numpy Array?
2. Wie legt man eine Pandas Dataframe an?
3. Wie liest man eine .csv Datei in einen Pandas Dataframe?
4. Wie schreibt man einen Pandas Dataframe in eine .csv Datei?
4. Wie greift man auf den Index eines Pandas Dataframes zu?
4. Wie greift man auf die Spaltennamen eines Dataframes zu?
5. Wie greift man auf eine Spalte eines Dataframes zu?
6. Wie greift man auf eine Zeile eines Dataframes zu?